# Generated by Django 6.0.6 on 2026-06-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=20)),
                ('ingresos_brutos', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio_actividades', models.DateField(blank=True, null=True)),
                ('condicion_iva', models.CharField(default='IVA Responsable Inscripto', max_length=50)),
                ('punto_venta_defecto', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Configuración de la empresa',
                'verbose_name_plural': 'Configuración de la empresa',
            },
        ),
    ]
