# Generated by Django 6.0.6 on 2026-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='leyenda',
            field=models.CharField(blank=True, help_text='Frase descriptiva que aparece al pie del comprobante', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='otros_impuestos_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje estimado de otros impuestos nacionales indirectos contenidos en el precio (Ley 27.743)', max_digits=5),
        ),
    ]
