# Generated by Django 6.0.6 on 2026-07-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0002_empresaconfig_leyenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='nombre_fantasia',
            field=models.CharField(blank=True, help_text='Nombre comercial/marca que se muestra como título del comprobante (si está vacío, se usa la Razón Social)', max_length=200),
        ),
        migrations.AlterField(
            model_name='empresaconfig',
            name='razon_social',
            field=models.CharField(help_text='Razón Social legal, tal como figura ante ARCA', max_length=200),
        ),
    ]
