# Generated by Django 6.0.6 on 2026-07-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0003_empresaconfig_nombre_fantasia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True, verbose_name='Servidor SMTP'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='email_password',
            field=models.CharField(blank=True, help_text="Para Gmail, usar una 'contraseña de aplicación', no la contraseña normal de la cuenta", max_length=255, null=True, verbose_name='Contraseña / clave de aplicación'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, null=True, verbose_name='Puerto SMTP'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='email_remitente',
            field=models.EmailField(blank=True, help_text='Cuenta desde la que se envían las facturas por email (ej. Gmail)', max_length=254, null=True, verbose_name='Email remitente'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Usar TLS'),
        ),
    ]
