# Generated by Django 6.0.6 on 2026-07-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0004_empresaconfig_email_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='email_nombre_remitente',
            field=models.CharField(blank=True, help_text="Nombre que va a ver el cliente como remitente del email (ej. 'Lic. Fernando Villares'). Si está vacío, se usa la Razón Social", max_length=100, null=True, verbose_name='Nombre del remitente'),
        ),
    ]
