# Generated by Django 6.0.6 on 2026-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0005_empresaconfig_email_nombre_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Tamaño sugerido: 400×160 px (relación 2.5:1), PNG con fondo transparente, para que se vea nítido en el comprobante impreso.', null=True, upload_to='empresa/', verbose_name='Logo'),
        ),
    ]
