# Generated by Django 6.0.6 on 2026-08-15 17:19

from django.db import migrations, models

from arca.crypto import cifrar, descifrar


def cifrar_password_existente(apps, schema_editor):
    EmpresaConfig = apps.get_model('arca', 'EmpresaConfig')
    for config in EmpresaConfig.objects.all():
        valor = config.email_password
        if not valor:
            continue
        if descifrar(valor):
            continue  # ya esta cifrado (idempotente si se corre dos veces)
        config.email_password = cifrar(valor)
        config.save(update_fields=['email_password'])


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0006_empresaconfig_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaconfig',
            name='email_password',
            field=models.CharField(blank=True, help_text="Para Gmail, usar una 'contraseña de aplicación', no la contraseña normal de la cuenta. Se guarda cifrada.", max_length=512, null=True, verbose_name='Contraseña / clave de aplicación'),
        ),
        migrations.RunPython(cifrar_password_existente, migrations.RunPython.noop),
    ]
