# Generated by Django 6.0.6 on 2026-08-15 17:28

import arca.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca', '0007_alter_empresaconfig_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Tamaño sugerido: 400×160 px (relación 2.5:1), PNG con fondo transparente, para que se vea nítido en el comprobante impreso. Máx. 5 MB.', null=True, upload_to='empresa/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), arca.models.validar_tamano_logo], verbose_name='Logo'),
        ),
    ]
