# Generated by Django 6.0.6 on 2026-08-15 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_contacto_soporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('origen', models.CharField(choices=[('REFERIDO', 'Referido'), ('REDES', 'Redes sociales'), ('WEB', 'Web'), ('OTRO', 'Otro')], default='OTRO', max_length=10)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CONTACTADO', 'Contactado'), ('NEGOCIACION', 'En negociación'), ('GANADO', 'Ganado'), ('PERDIDO', 'Perdido')], default='NUEVO', max_length=12)),
                ('proximo_contacto', models.DateField(blank=True, null=True, verbose_name='Próximo contacto')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, help_text='Se actualiza sola en cada cambio.')),
                ('cliente', models.ForeignKey(blank=True, help_text='Se completa solo al convertir el lead en Cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='clientes.cliente', verbose_name='Cliente (una vez convertido)')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='NotaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Nota de lead',
                'verbose_name_plural': 'Notas de lead',
                'ordering': ['-fecha'],
            },
        ),
    ]
