# Generated by Django 6.0.6 on 2026-08-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTA', 'Nota'), ('LLAMADA', 'Llamada'), ('REUNION', 'Reunión')], default='NOTA', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(help_text='Cuándo pasó (si ya está hecha) o cuándo vence (si no).', verbose_name='Fecha')),
                ('hecha', models.BooleanField(default=False, verbose_name='Hecha')),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
