# Generated by Django 6.0.6 on 2026-06-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dni',
            new_name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cuit',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('80', 'CUIT'), ('86', 'CUIL'), ('96', 'DNI'), ('87', 'CDI'), ('99', 'Consumidor Final (Sin identificar)')], default='96', max_length=2),
        ),
    ]
