# Generated by Django 6.0.6 on 2026-06-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaitem',
            name='alicuota_iva',
            field=models.CharField(choices=[('3', '0%'), ('4', '10.5%'), ('5', '21%'), ('6', '27%'), ('8', '5%'), ('9', '2.5%')], max_length=2),
        ),
    ]
