# Generated by Django 6.0.6 on 2026-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_facturaitem_alicuota_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='condicion_venta',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CUENTA_CORRIENTE', 'Cuenta Corriente'), ('TARJETA', 'Tarjeta')], default='TRANSFERENCIA', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vto_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='periodo_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='periodo_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
