# Generated by Django 6.0.6 on 2026-06-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_factura_condicion_venta_factura_fecha_vto_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_vto_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento para el pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='periodo_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Período facturado desde'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='periodo_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Período facturado hasta'),
        ),
    ]
