# Generated by Django 6.0.6 on 2026-06-14 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_factura_fecha_vto_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='factura_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_relacionadas', to='facturas.factura', verbose_name='Comprobante asociado (para Notas de Crédito/Débito)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_comprobante',
            field=models.CharField(choices=[('1', 'Factura A'), ('6', 'Factura B'), ('11', 'Factura C'), ('2', 'Nota de Débito A'), ('7', 'Nota de Débito B'), ('12', 'Nota de Débito C'), ('3', 'Nota de Crédito A'), ('8', 'Nota de Crédito B'), ('13', 'Nota de Crédito C')], default='6', max_length=2),
        ),
    ]
