# Generated by Django 6.0.6 on 2026-06-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_dni_cliente_numero_documento_and_more'),
        ('facturas', '0005_factura_factura_asociada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturaitem',
            options={'verbose_name': 'Línea de factura', 'verbose_name_plural': 'Líneas de factura'},
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('punto_venta', 'tipo_comprobante', 'numero'), name='numero_comprobante_unico_por_pto_vta_y_tipo'),
        ),
    ]
