# Generated by Django 6.0.6 on 2026-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_alter_facturaitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='motivo_nota',
            field=models.CharField(blank=True, choices=[('DESCUENTO_PARCIAL', 'Descuento parcial'), ('DEVOLUCION_PARCIAL', 'Devolución parcial de producto/servicio'), ('ANULACION_TOTAL', 'Anulación total del comprobante'), ('ERROR_FACTURACION', 'Error de facturación'), ('OTRO', 'Otro')], help_text='Solo aplica a Notas de Crédito/Débito.', max_length=20, null=True, verbose_name='Motivo de la nota'),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_nota_detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del motivo'),
        ),
    ]
