# Generated by Django 6.0.6 on 2026-07-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_factura_motivo_nota_factura_motivo_nota_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='entorno_emision',
            field=models.CharField(blank=True, choices=[('homologacion', 'Homologación'), ('produccion', 'Producción')], help_text='Se completa automáticamente al pedir el CAE. Permite identificar y borrar facturas de prueba emitidas en homologación.', max_length=20, null=True, verbose_name='Entorno de emisión'),
        ),
    ]
