# Generated by Django 6.0.6 on 2026-07-03 16:33

from django.db import migrations, models


def mover_observaciones_a_error_arca(apps, schema_editor):
    """Antes, `observaciones` guardaba tanto el detalle de rechazo de ARCA
    (para facturas en estado ERROR) como notas libres. Se separan en dos
    campos: el texto existente en facturas rechazadas se preserva pasándolo
    a `error_arca`, para no perder el detalle del rechazo ni confundirlo
    con una nota real."""
    Factura = apps.get_model('facturas', 'Factura')
    Factura.objects.filter(estado='ERROR', observaciones__isnull=False).update(
        error_arca=models.F('observaciones'), observaciones=None,
    )


def revertir(apps, schema_editor):
    Factura = apps.get_model('facturas', 'Factura')
    Factura.objects.filter(estado='ERROR', error_arca__isnull=False).update(
        observaciones=models.F('error_arca'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_factura_entorno_emision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='motivo_nota',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='motivo_nota_detalle',
        ),
        migrations.AddField(
            model_name='factura',
            name='error_arca',
            field=models.TextField(blank=True, help_text='Se completa automáticamente si ARCA rechaza el comprobante.', null=True, verbose_name='Detalle de rechazo de ARCA'),
        ),
        migrations.AddField(
            model_name='facturaitem',
            name='descripcion_personalizada',
            field=models.CharField(blank=True, help_text='Si se completa, reemplaza el nombre del producto/servicio solo en esta línea, sin modificar el catálogo.', max_length=255, null=True, verbose_name='Descripción personalizada'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Texto libre que se muestra en el comprobante, entre los productos y los totales.', null=True, verbose_name='Notas'),
        ),
        migrations.RunPython(mover_observaciones_a_error_arca, revertir),
    ]
