# Generated by Django 6.0.6 on 2026-07-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0010_servicio_opcional_en_item'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaitem',
            name='descripcion_personalizada',
            field=models.CharField(blank=True, help_text='Si elegiste un Servicio, reemplaza su nombre solo en esta línea sin modificar el catálogo. Si no elegiste ningún Servicio, este es el nombre del producto personalizado.', max_length=255, null=True, verbose_name='Descripción personalizada'),
        ),
        migrations.AlterField(
            model_name='facturaitem',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text="Dejalo vacío para cargar un producto personalizado (completá el nombre en 'Descripción personalizada' y el precio a mano).", null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio'),
        ),
    ]
