# Generated by Django 6.0.6 on 2026-07-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_dni_cliente_numero_documento_and_more'),
        ('facturas', '0012_factura_estado_emitiendo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='factura',
            name='numero_comprobante_unico_por_pto_vta_y_tipo',
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('entorno_emision', 'punto_venta', 'tipo_comprobante', 'numero'), name='numero_comprobante_unico_por_entorno_pto_vta_y_tipo'),
        ),
    ]
