# Generated by Django 6.0.6 on 2026-07-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0014_factura_cobro_retenciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, help_text='Se actualiza sola en cada cambio. Usado para detectar cambios desde otros dispositivos sin recargar la página.'),
        ),
    ]
